export const PENDING_CHALLENGES_LOADING = 'PENDING_CHALLENGES_LOADING';
export const PENDING_CHALLENGES_SUCCESS = 'PENDING_CHALLENGES_SUCCESS';
export const PENDING_CHALLENGES_FAILURE = 'PENDING_CHALLENGES_FAILURE';
export const COMPLETED_CHALLENGES = 'COMPLETED_CHALLENGES';
